# Generated by Django 4.2.1 on 2023-05-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=182, null=True)),
                ('image', models.ImageField(upload_to='dishes_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Сheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cheque', models.DecimalField(decimal_places=2, max_digits=6)),
                ('set_menu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.dish')),
                ('id_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.dish')),
                ('id_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.сheque')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('id_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.сheque')),
            ],
        ),
    ]
