# Generated by Django 4.2.1 on 2023-06-04 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishcomplexdish',
            name='complex_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dish.complexdish'),
        ),
        migrations.AddField(
            model_name='dishcomplexdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dish.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='id_type_dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.typedish'),
        ),
        migrations.AddField(
            model_name='basket',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dish.dish'),
        ),
        migrations.AddField(
            model_name='basket',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
